language: haskell

notifications:
  email:
    recipients:
      - roland@tritsch.org
    on_success: always
    on_failure: always

before_install:
  - curl -sSL https://get.haskellstack.org/ | sh

script:
  - stack test
  - stack build
  - stack exec haskell-aoc
