name:                haskell-aoc
version:             0.1.0.0
github:              "rolandtritsch/haskell-aoc-2017"
license:             BSD3
author:              "Roland Tritsch"
maintainer:          "roland@tritsch.org"
copyright:           "2018 Roland Tritsch"

extra-source-files:
- README.md

synopsis:            An implementation of the Advent of Code - 2017
category:            Web

description:         Please see the README on Github

dependencies:
- base >= 4.7 && < 5
- containers
- timeit
- async
- stm

library:
  source-dirs:       src
  ghc-options:
  - -O2
  - -Wall -Werror
  dependencies:
  - text
  - split
  - hexstring
  - Unique

executables:
  haskell-aoc:
    main:            Main.hs
    source-dirs:     app
    ghc-options:
    - -main-is Main.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc

  haskell-aoc-day01p1:
    main:            src/Day01/Part1.hs
    ghc-options:
    - -main-is Day01.Part1.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc

  haskell-aoc-day01p2:
    main:            src/Day01/Part2.hs
    ghc-options:
    - -main-is Day01.Part2.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc

  haskell-aoc-day02p1:
    main:            src/Day02/Part1.hs
    ghc-options:
    - -main-is Day02.Part1.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc

  haskell-aoc-day02p2:
    main:            src/Day02/Part2.hs
    ghc-options:
    - -main-is Day02.Part2.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc

  haskell-aoc-day03p1:
    main:            src/Day03/Part1.hs
    ghc-options:
    - -main-is Day03.Part1.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc

  haskell-aoc-day03p2:
    main:            src/Day03/Part2.hs
    ghc-options:
    - -main-is Day03.Part2.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc

  haskell-aoc-day04p1:
    main:            src/Day04/Part1.hs
    ghc-options:
    - -main-is Day04.Part1.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc

  haskell-aoc-day04p2:
    main:            src/Day04/Part2.hs
    ghc-options:
    - -main-is Day04.Part2.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc

  haskell-aoc-day05p1:
    main:            src/Day05/Part1.hs
    ghc-options:
    - -main-is Day05.Part1.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc

  haskell-aoc-day05p2:
    main:            src/Day05/Part2.hs
    ghc-options:
    - -main-is Day05.Part2.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc

  haskell-aoc-day06p1:
    main:            src/Day06/Part1.hs
    ghc-options:
    - -main-is Day06.Part1.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc

  haskell-aoc-day06p2:
    main:            src/Day06/Part2.hs
    ghc-options:
    - -main-is Day06.Part2.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc

  haskell-aoc-day07p1:
    main:            src/Day07/Part1.hs
    ghc-options:
    - -main-is Day07.Part1.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc

  haskell-aoc-day07p2:
    main:            src/Day07/Part2.hs
    ghc-options:
    - -main-is Day07.Part2.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc

  haskell-aoc-day08p1:
    main:            src/Day08/Part1.hs
    ghc-options:
    - -main-is Day08.Part1.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc

  haskell-aoc-day08p2:
    main:            src/Day08/Part2.hs
    ghc-options:
    - -main-is Day08.Part2.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc

  haskell-aoc-day09p1:
    main:            src/Day09/Part1.hs
    ghc-options:
    - -main-is Day09.Part1.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc

  haskell-aoc-day09p2:
    main:            src/Day09/Part2.hs
    ghc-options:
    - -main-is Day09.Part2.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc

  haskell-aoc-day10p1:
    main:            src/Day10/Part1.hs
    ghc-options:
    - -main-is Day10.Part1.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc

  haskell-aoc-day10p2:
    main:            src/Day10/Part2.hs
    ghc-options:
    - -main-is Day10.Part2.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc

  haskell-aoc-day11p1:
    main:            src/Day11/Part1.hs
    ghc-options:
    - -main-is Day11.Part1.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc

  haskell-aoc-day11p2:
    main:            src/Day11/Part2.hs
    ghc-options:
    - -main-is Day11.Part2.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc

  haskell-aoc-day12p1:
    main:            src/Day12/Part1.hs
    ghc-options:
    - -main-is Day12.Part1.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc

  haskell-aoc-day12p2:
    main:            src/Day12/Part2.hs
    ghc-options:
    - -main-is Day12.Part2.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc

  haskell-aoc-day13p1:
    main:            src/Day13/Part1.hs
    ghc-options:
    - -main-is Day13.Part1.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc

  haskell-aoc-day13p2:
    main:            src/Day13/Part2.hs
    ghc-options:
    - -main-is Day13.Part2.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc

  haskell-aoc-day14p1:
    main:            src/Day14/Part1.hs
    ghc-options:
    - -main-is Day14.Part1.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc

  haskell-aoc-day14p2:
    main:            src/Day14/Part2.hs
    ghc-options:
    - -main-is Day14.Part2.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc

  haskell-aoc-day15p1:
    main:            src/Day15/Part1.hs
    ghc-options:
    - -main-is Day15.Part1.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc

  haskell-aoc-day15p2:
    main:            src/Day15/Part2.hs
    ghc-options:
    - -main-is Day15.Part2.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc

  haskell-aoc-day16p1:
    main:            src/Day16/Part1.hs
    ghc-options:
    - -main-is Day16.Part1.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc

  haskell-aoc-day16p2:
    main:            src/Day16/Part2.hs
    ghc-options:
    - -main-is Day16.Part2.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc

  haskell-aoc-day17p1:
    main:            src/Day17/Part1.hs
    ghc-options:
    - -main-is Day17.Part1.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc

  haskell-aoc-day17p2:
    main:            src/Day17/Part2.hs
    ghc-options:
    - -main-is Day17.Part2.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc

  haskell-aoc-day18p1:
    main:            src/Day18/Part1.hs
    ghc-options:
    - -main-is Day18.Part1.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc

  haskell-aoc-day18p2:
    main:            src/Day18/Part2.hs
    ghc-options:
    - -main-is Day18.Part2.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc

  haskell-aoc-day19p1:
    main:            src/Day19/Part1.hs
    ghc-options:
    - -main-is Day19.Part1.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc

  haskell-aoc-day19p2:
    main:            src/Day19/Part2.hs
    ghc-options:
    - -main-is Day19.Part2.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc

  haskell-aoc-day20p1:
    main:            src/Day20/Part1.hs
    ghc-options:
    - -main-is Day20.Part1.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc

  haskell-aoc-day20p2:
    main:            src/Day20/Part2.hs
    ghc-options:
    - -main-is Day20.Part2.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc

tests:
  haskell-aoc-test:
    main:            Spec.hs
    source-dirs:     test
    ghc-options:
    - -main-is Spec.main
    dependencies:
    - haskell-aoc
    - hspec

  haskell-aoc-test-day01:
    main:            Day01Spec.hs
    source-dirs:     test
    other-modules:   Day01Spec
    ghc-options:
    - -main-is Day01Spec.run
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - hspec

  haskell-aoc-test-day02:
    main:            Day02Spec.hs
    source-dirs:     test
    other-modules:   Day02Spec
    ghc-options:
    - -main-is Day02Spec.run
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - hspec

  haskell-aoc-test-day03:
    main:            Day03Spec.hs
    source-dirs:     test
    other-modules:   Day03Spec
    ghc-options:
    - -main-is Day03Spec.run
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - hspec

  haskell-aoc-test-day04:
    main:            Day04Spec.hs
    source-dirs:     test
    other-modules:   Day04Spec
    ghc-options:
    - -main-is Day04Spec.run
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - hspec

  haskell-aoc-test-day05:
    main:            Day05Spec.hs
    source-dirs:     test
    other-modules:   Day05Spec
    ghc-options:
    - -main-is Day05Spec.run
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - hspec

  haskell-aoc-test-day06:
    main:            Day06Spec.hs
    source-dirs:     test
    other-modules:   Day06Spec
    ghc-options:
    - -main-is Day06Spec.run
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - hspec

  haskell-aoc-test-day07:
    main:            Day07Spec.hs
    source-dirs:     test
    other-modules:   Day07Spec
    ghc-options:
    - -main-is Day07Spec.run
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - hspec

  haskell-aoc-test-day08:
    main:            Day08Spec.hs
    source-dirs:     test
    other-modules:   Day08Spec
    ghc-options:
    - -main-is Day08Spec.run
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - hspec

  haskell-aoc-test-day09:
    main:            Day09Spec.hs
    source-dirs:     test
    other-modules:   Day09Spec
    ghc-options:
    - -main-is Day09Spec.run
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - hspec

  haskell-aoc-test-day10:
    main:            Day10Spec.hs
    source-dirs:     test
    other-modules:   Day10Spec
    ghc-options:
    - -main-is Day10Spec.run
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - hspec

  haskell-aoc-test-day11:
    main:            Day11Spec.hs
    source-dirs:     test
    other-modules:   Day11Spec
    ghc-options:
    - -main-is Day11Spec.run
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - hspec

  haskell-aoc-test-day12:
    main:            Day12Spec.hs
    source-dirs:     test
    other-modules:   Day12Spec
    ghc-options:
    - -main-is Day12Spec.run
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - hspec

  haskell-aoc-test-day13:
    main:            Day13Spec.hs
    source-dirs:     test
    other-modules:   Day13Spec
    ghc-options:
    - -main-is Day13Spec.run
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - hspec

  haskell-aoc-test-day14:
    main:            Day14Spec.hs
    source-dirs:     test
    other-modules:   Day14Spec
    ghc-options:
    - -main-is Day14Spec.run
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - hspec

  haskell-aoc-test-day15:
    main:            Day15Spec.hs
    source-dirs:     test
    other-modules:   Day15Spec
    ghc-options:
    - -main-is Day15Spec.run
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - hspec

  haskell-aoc-test-day16:
    main:            Day16Spec.hs
    source-dirs:     test
    other-modules:   Day16Spec
    ghc-options:
    - -main-is Day16Spec.run
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - hspec

  haskell-aoc-test-day17:
    main:            Day17Spec.hs
    source-dirs:     test
    other-modules:   Day17Spec
    ghc-options:
    - -main-is Day17Spec.run
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - hspec

  haskell-aoc-test-day18:
    main:            Day18Spec.hs
    source-dirs:     test
    other-modules:   Day18Spec
    ghc-options:
    - -main-is Day18Spec.run
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - hspec

  haskell-aoc-test-day19:
    main:            Day19Spec.hs
    source-dirs:     test
    other-modules:   Day19Spec
    ghc-options:
    - -main-is Day19Spec.run
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - hspec

  haskell-aoc-test-day20:
    main:            Day20Spec.hs
    source-dirs:     test
    other-modules:   Day20Spec
    ghc-options:
    - -main-is Day20Spec.run
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - hspec
